### ISSUE TITLE
gulp build-dev error

### ISSUE THREAD

**Issue by dcasciotti** [flauc/angular2-edge-app#1]
Hi,
i received this error when running the gulp build-dev command in terminal.
Thank you for your consideration of this matter.
Dave casciotti

/Users/davidcasciotti/angular2-edge-app/gulpfile.js:50
gulp.task('move-vendorJs', ()=> {
                            ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/share/npm/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/share/npm/lib/node_modules/gulp/node_modules/liftoff/index.js:181:16)
    at module.exports (/usr/local/share/npm/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/share/npm/lib/node_modules/gulp/node_modules/liftoff/index.js:174:9)

**Comment by flauc** [comment]
Hi @dcasciotti 

Thanks for reporting the issue. The application is still a work in progress so please report any error you find, and i'll have it fixed as soon as possible.

**Comment by flauc** [comment]
Hi again,

If you pull the latest build everything should be working for you. Let me know how it goes :+1:

**Comment by dcasciotti** [comment]
Hi 

Getting this when starting server.

Thanks

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/share/npm/bin/npm" "run" "server"
npm ERR! node v4.4.7
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE
npm ERR! angular2-edge-app@0.0.1 server: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-edge-app@0.0.1 server script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-edge-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-edge-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-edge-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/davidcasciotti/angular2-edge-app-master/npm-debug.log
